C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:21
            .then((response)){
                             ^

SyntaxError: Unexpected token '{'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jason\Desktop\server\controllers\transaction.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:9128) UnhandledPromiseRejectionWarning: ReferenceError: rawtx is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:39:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:9128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8608) UnhandledPromiseRejectionWarning: ReferenceError: rawtx is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:39:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:8608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12328) UnhandledPromiseRejectionWarning: ReferenceError: rawtx is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:39:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:12328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:35
                    axios.({
                          ^

SyntaxError: Unexpected token '('
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jason\Desktop\server\controllers\transaction.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
***Response***
2020/06/05 - 18:46:40
RpcError: Could not find block: 124460542
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:47:51
RpcError: Could not find block: 124460682
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:48:41
RpcError: Could not find block: 124460786
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:49:36
RpcError: Could not find block: 124460894
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:51:24
RpcError: Could not find block: 124461110
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:53:01
RpcError: Could not find block: 124461302
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 18:55:07
[
  {
    message: 'Could not find block: 124461554',
    file: 'chain_plugin.cpp',
    line_number: 2073,
    method: 'get_block'
  }
]
***Response***
2020/06/05 - 19:08:36
(node:11636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at C:\Users\Jason\Desktop\server\coin_source_code\eos\trans.js:64:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
***Response***
2020/06/05 - 19:09:18
(node:10220) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
    at C:\Users\Jason\Desktop\server\coin_source_code\eos\trans.js:64:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
***Response***
2020/06/05 - 19:10:42
FetchError: request to https://eos.greymass.com:443/v1/chain/get_info failed, reason: getaddrinfo ENOTFOUND eos.greymass.com
    at ClientRequest.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to https://eos.greymass.com:443/v1/chain/get_info failed, reason: getaddrinfo ENOTFOUND eos.greymass.com',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  isFetchError: true
}
7 - Broadcast Server Down
***Response***
2020/06/05 - 19:11:18
FetchError: request to https://eos.greymass.com:443/v1/chain/get_info failed, reason: getaddrinfo ENOTFOUND eos.greymass.com
    at ClientRequest.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to https://eos.greymass.com:443/v1/chain/get_info failed, reason: getaddrinfo ENOTFOUND eos.greymass.com',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  isFetchError: true
}
7 - Broadcast Server Down
***Response***
2020/06/05 - 19:11:57
RpcError: Could not find block: 124463574
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 19:13:33
RpcError: Could not find block: 124463766
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 19:13:58
RpcError: Could not find block: 124463818
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 19:15:04
RpcError: Could not find block: 124463949
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 19:19:34
RpcError: Could not find block: 124464488
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
***Response***
2020/06/05 - 19:20:06
RpcError: Could not find block: 124464556
    at new RpcError (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (C:\Users\Jason\Desktop\server\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  json: {
    code: 400,
    message: 'Unknown Block',
    error: {
      code: 3100002,
      name: 'unknown_block_exception',
      what: 'Unknown block',
      details: [Array]
    }
  }
}
Invalid Argument: Amount is expected to be a positive integer
Error
    at new NodeError (C:\Users\Jason\Desktop\server\node_modules\bsv\lib\errors\index.js:20:41)
    at Object.checkArgument (C:\Users\Jason\Desktop\server\node_modules\bsv\lib\util\preconditions.js:14:13)
    at Transaction.to (C:\Users\Jason\Desktop\server\node_modules\bsv\lib\transaction\transaction.js:724:5)
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:39:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'Invalid Argument: Amount is expected to be a positive integer',
  stack: 'Invalid Argument: Amount is expected to be a positive integer\n' +
    'Error\n' +
    '    at new NodeError (C:\\Users\\Jason\\Desktop\\server\\node_modules\\bsv\\lib\\errors\\index.js:20:41)\n' +
    '    at Object.checkArgument (C:\\Users\\Jason\\Desktop\\server\\node_modules\\bsv\\lib\\util\\preconditions.js:14:13)\n' +
    '    at Transaction.to (C:\\Users\\Jason\\Desktop\\server\\node_modules\\bsv\\lib\\transaction\\transaction.js:724:5)\n' +
    '    at C:\\Users\\Jason\\Desktop\\server\\coin_source_code\\bsv\\trans.js:39:26\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
(node:9940) UnhandledPromiseRejectionWarning: ReferenceError: api is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:24:19
    at new Promise (<anonymous>)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:22:19)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\controllers\transaction.js:41:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:284:7
(node:9940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2512) UnhandledPromiseRejectionWarning: ReferenceError: api is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:24:19
    at new Promise (<anonymous>)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:22:19)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\controllers\transaction.js:41:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:284:7
(node:2512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11296) UnhandledPromiseRejectionWarning: ReferenceError: api is not defined
    at C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:24:19
    at new Promise (<anonymous>)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\coin_source_code\bsv\trans.js:22:19)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\controllers\transaction.js:41:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:284:7
(node:11296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module './node_modules/express'
Require stack:
- C:\Users\Jason\Desktop\server\Routes\routes.js
- C:\Users\Jason\Desktop\server\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jason\Desktop\server\Routes\routes.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Jason\\Desktop\\server\\Routes\\routes.js',
    'C:\\Users\\Jason\\Desktop\\server\\app.js'
  ]
}
^C(node:13284) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Jason\Desktop\server\Logging/../../Logs/ETH/Trans/2020_06_06.log'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at Object.exports.log (C:\Users\Jason\Desktop\server\Logging\logger.js:7:8)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\Currencies\ETH\trans.js:12:12)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\Controllers\transaction.js:116:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\node_modules\express\lib\router\index.js:317:13)
(node:13284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jason\Desktop\server\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
C:\Users\Jason\Desktop\server\App\Logging\logger.js:9
    fs.appendFileSync(directory, message)
    ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jason\Desktop\server\App\Currencies\ETH\trans.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Jason\Desktop\server\App\Controllers\transaction.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
(node:12916) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\Jason\Desktop\server\App\Logging/../../Logs/ETH/Trans/2020_06_06.log'
    at Object.statSync (fs.js:915:3)
    at Object.exports.log (C:\Users\Jason\Desktop\server\App\Logging\logger.js:8:12)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\App\Currencies\ETH\trans.js:12:12)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\App\Controllers\transaction.js:116:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:284:7
(node:12916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12632) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'C:\Users\Jason\Desktop\server\App\Logging/../../Logs/ETH/Trans/2020_06_06.log'
    at Object.statSync (fs.js:915:3)
    at Object.exports.log (C:\Users\Jason\Desktop\server\App\Logging\logger.js:8:12)
    at Object.exports.trans (C:\Users\Jason\Desktop\server\App\Currencies\ETH\trans.js:12:12)
    at exports.postTransaction (C:\Users\Jason\Desktop\server\App\Controllers\transaction.js:116:37)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jason\Desktop\server\App\node_modules\express\lib\router\index.js:284:7
(node:12632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
